FROM quay.io/quarkus/quarkus-micro-image:2.0

COPY fly/target/*-runner /deployments/application

RUN chmod a+x /deployments/*

CMD ./deployments/application                                               \
         -Dquarkus.http.host=0.0.0.0                                        \
         -Dquarkus.datasource.reactive.url=$DATABASE_URL                    \
         -Dquarkus.hibernate-orm.log.sql=true                               \
         -Dquarkus.hibernate-orm.database.generation=create
