# fly.toml app configuration file generated for k0c3-task-manager on 2023-12-04T11:38:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "k0c3-task-manager"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
DATABASE_URL="jdbc:postgres://postgres:92Sk3TWRbfLQLll@task-postgres.flycast:5432/k0c3_task_manager&sslmode=disable"

[experimental]
  auto_rollback = true

[build]
  image = "kgeorgiev86/task-manager-reactive:fly"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
